### ISSUE TITLE
Remove auto-downloading?

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/pyensembl#101]
Seems like it might be an unnecessary headache, per a conversation with @iskandr. We might just want to require users to manually install via `pyensembl install` or within Python.

**Comment by hammer** [comment]
:+1: Please call it `download` not `install` though.

**Comment by tavinathanson** [comment]
@hammer there's currently `pyensembl install`, `pyensembl index` and `pyensembl download`

`download`: downloads GTF/FASTA files from a server (or, if they're local, just copies them from the local location).
`index`: creates a DB for GTF data and indexes FASTA files.
`install`: `download` + `index`

@iskandr have been hoping for better names, here. Thoughts?

**Comment by hammer** [comment]
`download` and `index` seem fine; how about `download_and_index`?

**Comment by tavinathanson** [comment]
Seems like a long name for something that's going to be (I assume) the most common command.

**Comment by hammer** [comment]
so give it a shortcut name like `dli` or something?

**Comment by tavinathanson** [comment]
While I don't love `install`, it seems easier to remember than `dli` or `download_and_index`. Curious what connotations you think `install` has that make it inappropriate?

**Comment by tavinathanson** [comment]
Naming discussion moved to https://github.com/hammerlab/pyensembl/issues/102

**Comment by tavinathanson** [comment]
Auto-downloading removed in #114
