### ISSUE TITLE
Organize cache subdirectories by species, reference, annotation source

### ISSUE THREAD

**Issue by iskandr** [hammerlab/pyensembl#109]
In my aborted attempt to fix the `any-gtf`I started reorganizing how cached files are organized. Instead of dumping anything into one directory, I would rather have something like `$CACHE_DIR/Homo_sapiesn/GRCh38/ensembl/79`. This would simplify clearing the cache for a particular `Genome` instance (just delete its subdirectory, since there would be a 1-1 correspondence between Genomes and cache subdirs). 

For a custom GTF/FASTA combo this would require the user specifying the species, reference  name, annotation source, and (optionally) an annotation version. That's can be a bit annoying, but custom data files are a special case which hopefully will arise rarely once we have "official" support for multiple species and annotation sources.

**Comment by JPFinnigan** [comment]
+1. But, if I could toss in my  $0.02. For end users (especially those who may have not have used the Ensembl website, and are perhaps used to Entrez/Uniprot) it's not obvious that genome == organism. Perhaps consider something more explicit. 

Eg:
from pyensembl import EnsemblRelease
data = Organism(Mouse) ReferenceAssembly(mm10/GRCm38) EnsemblRelease(81)

**Comment by iskandr** [comment]
@JPFinnigan What I was imagining was something like:

```
# figures out which reference to use for an ensembl dataset
data1 = Ensembl(release=81, species="mouse")
# figures out the species and the most recent release for the given genome
data2 = Ensembl(reference="GRCm38")
```

Is that too automagical? Would it be better to force the user to manually specify all three each time?

**Comment by JPFinnigan** [comment]
"Is that too automagical? Would it be better to force the user to manually specify all three each time?"

No, but it may be simpler in the end if you force the user to specify all three. This way you don't run into issues with an end user who has data aligned to a particular reference (e.g GRCm37) running varcode/topiary w/ the wrong Ensembl release (e.g 81). It would also afford the user/user group interested in analyzing a large cohort of subjects the opportunity to run varcode/topiary w/ consistent parameters across all subjects if, for example, a new Ensembl release went public in the middle of their project.

**Comment by iskandr** [comment]
Settled on ``$CACHE_DIR/Homo_sapiens/GRCh38/ensembl79` for directories and forcing users to specifying species and release as arguments to `EnsemblRelease` (from which the reference is inferred).
