### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by tommycarstensen** [hammerlab/pyensembl#123]
I did git clone and python setup.py install and got this error message despite having the latest version of setuptools:

Installed /software/team149/lib/python3.4/site-packages/six-1.9.0-py3.4.egg
Searching for mock>=1.0.1
Reading https://pypi.python.org/simple/mock/
Best match: mock 1.3.0
Downloading https://pypi.python.org/packages/source/m/mock/mock-1.3.0.tar.gz#md5=73ee8a4afb3ff4da1b4afa287f39fdeb
Processing mock-1.3.0.tar.gz
Writing /tmp/easy_install-t8kyy08i/mock-1.3.0/setup.cfg
Running mock-1.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-t8kyy08i/mock-1.3.0/egg-dist-tmp-5evvasqn
mock requires setuptools>=17.1. Aborting installation
error: Setup script exited with 1

**Comment by iskandr** [comment]
@tommycarstensen Possibly related to this issue? https://github.com/testing-cabal/mock/issues/261 

@tavinathanson We don't seem to use `mock` for anything, mind if I remove it?

**Comment by tavinathanson** [comment]
Go for it @iskandr

**Comment by iskandr** [comment]
@tommycarstensen Is it installing for you now?
