### ISSUE TITLE
Specifying install location 

### ISSUE THREAD

**Issue by rpadmanabhan** [hammerlab/pyensembl#145]
Hi,
Is there a way to specify a prefix when using pyensembl install to install the ensembl data to a particular directory.

Thank You

**Comment by iskandr** [comment]
@rpadmanabhan 

It's not currently possible to do that in a sane way but is sort-of possible if you don't mind reaching into the internals of pyensembl: you can pass a `cache_directory_path` argument when building a [Genome](https://github.com/hammerlab/pyensembl/blob/master/pyensembl/genome.py#L52). Unfortunately, we never exposed that as an option in [EnsemblRelease](https://github.com/hammerlab/pyensembl/blob/master/pyensembl/ensembl_release.py). 

I'll fix this for you in the next few days (at least from the Python interface for `EnsemblRelease`).

**Comment by rpadmanabhan** [comment]
ah i see , i will try messing around with it and see if it works for me.  Thanks
