### ISSUE TITLE
Manipulating Gene and Transcript objects.

### ISSUE THREAD

**Issue by superDross** [hammerlab/pyensembl#152]
Hi this may be a bit of a noob question so I am sorry if the solution is rather simple/obvious. Nevertheless, I have no idea how to properly manipulate a Gene or Transcript object that is returned and I am currently using regex to manipulate each element of the gene object. I was wondering if there is a better way to do this?

an example below:
```
def get_gene_info(hg, chorm, pos):
            gene_name = hg.gene_names_at_locus(contig=chrom, position=pos)
            gene_info = hg.genes_by_name(gene_name[0])
            # not sure how to manipulate Gene() object correctly so splitting will do and 
            #reorganise as a tuple
            gene_info_split = re.split(r"[=,]",str(gene_info[0]))
            gene_id = gene_info_split[1]
            gene_type = gene_info_split[5]
            gene_range = gene_info_split[7][:-1]

            gene_info = (gene_name[0], gene_id, gene_type, gene_range)

            return(gene_info)
```

**Comment by iskandr** [comment]
Hey @superDross, 

You could alternatively access fields of the `Gene` this:

```
