### ISSUE TITLE
Ensembl - Release 85

### ISSUE THREAD

**Issue by ericloud** [hammerlab/pyensembl#161]
Hi, 

It's possible to add human release 85.
Or explain, how we can fix it in your local installation.

Thanks,
Eric.

**Comment by ericloud** [comment]
Maybe it's a good idea to check if the URL exist, compare to save the max release in the constant MAX_ENSEMBL_RELEASE in ensembl_release_versions.py. This solution avoids to update the code at each new release.

**Comment by ericloud** [comment]
Ok we can install it, but I don't find the way to use it:
ensembl = EnsemblRelease(85)
Traceback (most recent call last):
  File "/u/eaudemard/dev/IRIC/tools/gene_prediction.py", line 331, in <module>
    main()
  File "/u/eaudemard/dev/IRIC/tools/gene_prediction.py", line 270, in main
    ensembl = EnsemblRelease(args.ENSEMBL)
  File "/soft/bioinfo/linux_RH7/python-2.7.10/lib/python2.7/site-packages/pyensembl/ensembl_release.py", line 39, in __init__
    self.release = check_release_number(release)
  File "/soft/bioinfo/linux_RH7/python-2.7.10/lib/python2.7/site-packages/pyensembl/ensembl_release_versions.py", line 33, in check_release_number
    release, MIN_ENSEMBL_RELEASE, MAX_ENSEMBL_RELEASE))
ValueError: Invalid Ensembl releases 85, must be between 54 and 84

**Comment by ericloud** [comment]
Modify  the code doesn't work enough!

ensembl.gene_name_of_transcript_id(select_id)
ValueError: Missing genome data file from ftp://ftp.ensembl.org/pub/release-85/gtf/homo_sapiens/Homo_sapiens.GRCh38.85.gtf.gz. Run pyensembl install --release 85 --species homo_sapiens

And "Run pyensembl install --release 85 --species homo_sapiens" doesn't help.

**Comment by iskandr** [comment]
Hi @ericloud, 

We've been incrementing the max release manually since (1) it affects how we set up tests for the library and (2) sometimes we have to fix non-obvious things to get a new release to work. Twice now the GTF format has been broken or changed from updated releases. I'll get PyEnsembl working with release 85 soon.

**Comment by ericloud** [comment]
Ok, thanks for your feedback.
