### ISSUE TITLE
Configurable cache location

### ISSUE THREAD

**Issue by joaoe** [hammerlab/pyensembl#167]
I'd like to be able to tell pyensembl to store and load genomes from a specific folder, so I can keep my data together with my projects, and being more easy to share the data between the many people using the same machine.

**Comment by arahuja** [comment]
@joaoe This can be managed through an environment variable: https://github.com/hammerlab/pyensembl#cache-location

Does this solve your issue?

**Comment by joaoe** [comment]
Eh, I was looking for this a couple months ago. Didn't find it. Was that a new addition ? Ok, solved then. Sorry for the noise.

**Comment by arahuja** [comment]
Yes, just recently added: https://github.com/hammerlab/pyensembl/pull/156, glad that works!

**Comment by joaoe** [comment]
Ok, this sucks a bit
```
def get_data_dir(subdir=None, envkey=None):
    if envkey and envkey in environ:
        return environ[envkey]
    if subdir is None:
        subdir = "datacache"
    return appdirs.user_cache_dir(subdir)
```

datacache/common.py is not appending the <ref_id>/<release_id> to the folder. So I can't just move previous cache folder which has both mouse and human data inside. I have to edit the variable every single time before constructing and getting a reference to a Genome().

**Comment by armish** [comment]
Hmm, this looks like it is a datacache issue rather than a pyensembl one, where datacache doesn't respect the `subdir` variable when constructing the full path.

@alex and others: where do you want me to fix this? Here within pyensembl or in datacache?
