### ISSUE TITLE
non-human or mouse species

### ISSUE THREAD

**Issue by JoseBlanca** [hammerlab/pyensembl#182]
Hi,

I've been checking you're library API and it looks very nice. Unfortunately I want to play with other species than human and mouse. The library keeps failing on me.
I've check the species.py file and it looks to me that human and mouse are the only available species. If that's the case it would be nice to put a warning in the REAME or, even better, to fix it.
Best,

Jose Blanca

**Comment by bibionid** [comment]
I'd really like to know the answer to this too - pyensembl is super useful already, but being able to access non-model species would be the icing on an already tasty cake. Any updates?
Thanks

**Comment by iskandr** [comment]
Hi @JoseBlanca and @bibionid, 

The way that we currently handle downloads requires a little bit of work to add each species. This is partially because the paths to GTF & FASTA files changes between species and Ensembl release on the FTP server. So, if you let me know which species you're interested in working with I can add them to the library.

**Comment by bibionid** [comment]
Hi @iskandr,
That's great, thanks for the swift response! It'd be ace if you could add Dog, Rat, and Chicken. 
Many thanks!

**Comment by iskandr** [comment]
@bibionid Should be fixed once we merge https://github.com/hammerlab/pyensembl/pull/183

**Comment by JoseBlanca** [comment]
Thanks for your answer and for the offer of adding more species. I am perfectly aware that adding more features to a library it can be a burden in the future and my use of those ENSEMBL datasets is not so extensive so I don't think is worth doing it just for my case.
Adding the list of the species supported to the documentation would be advisable though.
Thanks for making the effort of providing this resource to the community.
Best,

Jose Blanca
