### ISSUE TITLE
PDB IDs from gene_ids?

### ISSUE THREAD

**Issue by tommycarstensen** [hammerlab/pyensembl#187]
Is it possible to get PDB IDs and/or Uniprot IDs from gene_ids and/or transcript_ids using PyEnsembl? Thanks.

**Comment by iskandr** [comment]
Hey @tommycarstensen -- theoretically it's possible but I've never looked into it. Do you know of a database mapping Ensembl IDs to PDB?

**Comment by tommycarstensen** [comment]
Hi @iskandr ! I asked around yesterday and it can now be achieved with BioDBNet of [bioservices](https://github.com/cokelaer/bioservices/) written by @cokelaer . I asked both of you after reading [the question "Can I map gene symbols to PDB ids?" on biostars.org](https://www.biostars.org/p/196777/) and not seeing a Python solution. Uniprot has this flat text file, which links PDB IDs to Uniprot IDs, and it seems to be updated frequently: http://www.uniprot.org/docs/pdbtosp.txt
