### ISSUE TITLE
Make data downloads explicit

### ISSUE THREAD

**Issue by iskandr** [hammerlab/pyensembl#31]
Instead of transparently downloading data the first time it's needed (which introduces unexpected delays), instead require the user to download a data source explicitly. 

```
ensembl = EnsemblRelease()
ensembl.download_annotations()
ensembl.download_transcript_sequences()
```

When a methods requires a data source which isn't yet available, raise an exception and tell the user to call the required download method.

**Comment by tavinathanson** [comment]
I'd expect the downloading to be runnable via an included command line script, which the pre-download error would suggest needs to be run.

**Comment by iskandr** [comment]
What's the advantage of doing it through a commandline script rather than with a designated Python function? It's sort of a nuisance to leave the ipython session for every distinct ensembl release. Also, it's unclear to me *where* you would download data to without the convenience of datacache.

**Comment by tavinathanson** [comment]
I'm not clear why the download location is a problem? We could even still use datacache if we wanted to, but just frontload the downloading?

As for a script: I'm imagining someone pip installing pyensembl and then using it in a project, only to have it throw `"Please run "pyensembl update" to download the necessary data."` That, to me, feels like a commandline thing. (Though I don't see the harm in exposing it for ipython usage, too.)

What do you mean re leaving ipython for every release?

**Comment by hammer** [comment]
I prefer making this work from Python rather than from a script. You can always wrap the Python function to be called from the command line as well if you think that would be helpful.

> What do you mean re leaving ipython for every release?

He means that if you want to run a script you'd have to exit to the shell, which isn't totally true, as IPython can execute shell commands.

**Comment by tavinathanson** [comment]
Oh, sorry for not being clear: a commandline script that would wrap Python is exactly what I meant. (I didn't even consider doing everything via a commandline script.)

**Comment by iskandr** [comment]
Ah, I thought you meant that this needed to be a shell script. 

To let the user run `pyensembl update`, wouldn't we need to add pyensembl to their PATH? I'm just wary of any extra complexity or possible annoyances when you can just run the code from Python.

**Comment by tavinathanson** [comment]
I figure we can just use http://www.scotttorborg.com/python-packaging/command-line-scripts.html#the-console-scripts-entry-point, like webdiff does?
