### ISSUE TITLE
Cut 0.0.0 release

### ISSUE THREAD

**Issue by hammer** [hammerlab/pyensembl#32]
Once we get to a relatively stable state it would be nice to have a release.

**Comment by hammer** [comment]
Hmm it looks like we are [releasing to PyPI](https://pypi.python.org/pypi/pyensembl). @iskandr, what do you think about also putting a source release up on GitHub so that the "releases" tab is synchronized with PyPI? Would that be useful or just extra work?

**Comment by iskandr** [comment]
@hammer Yeah, I've been versioning for PyPI's benefit. I can `git tag` future releases, I don't think it's too much work.
