### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by hammer** [hammerlab/pyensembl#40]
Cf. [guac's](https://github.com/hammerlab/guacamole/blob/master/CONTRIBUTING.md), [ketrew's](https://github.com/hammerlab/ketrew/blob/master/CONTRIBUTING.md), and [cycledash's](https://github.com/hammerlab/cycledash/blob/master/CONTRIBUTING.md).

**Comment by hammer** [comment]
@iskandr could you knock out something quickly for this issue before the blog post?

**Comment by iskandr** [comment]
Added.
