### ISSUE TITLE
Use typechecks library for checking argument types

### ISSUE THREAD

**Issue by iskandr** [hammerlab/pyensembl#51]

**Comment by raonyguimaraes** [comment]
I'm receiving this error while trying to install this project:
File "/home/raony/.virtualenvs/genes/local/lib/python2.7/site-packages/pyensembl/database.py", line 24, in <module>
    from .type_checks import require_integer, require_string
ImportError: No module named type_checks

**Comment by iskandr** [comment]
Hey @raonyguimaraes, not sure if your comment got deleted but your problem was due to us not having the latest pyensembl on PyPI. If you try upgrading it should work now, thanks for letting me know there was an issue.
