### ISSUE TITLE
Switch from BioPython to skbio

### ISSUE THREAD

**Issue by iskandr** [hammerlab/pyensembl#71]
[Scikit-Bio](http://scikit-bio.org/) has a nicer API and is being actively developed by Rob Knight's lab.

**Comment by hammer** [comment]
:+1:

**Comment by tavinathanson** [comment]
BioPython has been giving us weird install errors, too. Thirded.

**Comment by iskandr** [comment]
No trace of BioPython in the repo left (only scikit-bio now)
